# file: .github/workflows/hello.yml
name: linter-gitHub-action
# on – определяет события, которые запускают воркфлоу
on: push
jobs:
  # build – произвольно выбранное имя задания
  # их может быть больше одного
  build:
    # операционная система для работы воркфлоу
    runs-on: ubuntu-latest
    steps: # список шагов, которые надо выполнить
      # экшен, выполняет какую-то задачу
      # checkout – клонирует репозиторий
      - uses: actions/checkout@v3
      # run – произвольная bash-команда
      # ls -la выведет содержимое текущего репозитория
      - name: 'install'
         run: npm i
      - name: 'lint'
         run: npx eslint .
      - name: 'Test & publish code coverage'
           uses: paambaati/codeclimate-action@v2.7.4
        env: 
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make covertest
          debug: true
